language: java

# speed up travis with repo caching https://docs.travis-ci.com/user/caching/
cache:
  directories:
    - $HOME/.m2

# 
install: mvn clean package install verify -Dcheckstyle.skip=true -Dgpg.skip=true -B -q -Pquickrun,examples

jdk:
  - openjdk8
  - openjdk11

before_script:
  - echo $HOME
  - echo $JAVA_OPTS
  - echo $MAVEN_OPTS
